RANDOM_STATE = 42

# SAMPLING
USE_STRATIFIED_SAMPLE = True
SAMPLE_SIZE = 20000

# TEXT CLEANING
MIN_TOKEN_LEN = 3

# TF-IDF
TFIDF_NGRAM_RANGE = (1, 2)
TFIDF_MIN_DF = 5
TFIDF_MAX_DF = 0.9
TFIDF_MAX_FEATURES = 50000

# TOPIC MODEL SELECTION
TOPIC_K_CANDIDATES = [5, 8, 10, 12, 15, 18]
COHERENCE_METRIC = "c_v"
TOP_N_WORDS = 12

# TOPIC MODELS 
N_TOPICS_NMF = 10
N_TOPICS_LDA = 10

# SENTENCE-BERT MODEL
SBERT_MODEL_NAME = "all-MiniLM-L6-v2"
